#!/bin/bash
# hermes-update-check — Stage 1: checks for updates, drops pending marker.
# Part of the hermes-auto-updater skill.
set -euo pipefail

HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
LOG_FILE="$HERMES_HOME/logs/auto-update.log"
PENDING_FILE="$HERMES_HOME/.pending-update"
CHECK_FILE="$HERMES_HOME/.last-update-check"

mkdir -p "$(dirname "$LOG_FILE")"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

# Load optional local notification config (generated by setup.sh)
NOTIFY_CONF="$HERMES_HOME/.auto-updater/notify.conf"

send_notification() {
    local msg="$1"
    if [ -f "$NOTIFY_CONF" ]; then
        # shellcheck source=/dev/null
        . "$NOTIFY_CONF"
        if [ -n "${NOTIFY_CMD:-}" ]; then
            eval "$NOTIFY_CMD" 2>/dev/null || true
        fi
    fi
}

if ! command -v hermes &>/dev/null; then
    log "ERROR: hermes not in PATH"
    exit 1
fi

log "Checking for updates..."
CHECK_OUTPUT=$(hermes update --check 2>&1) || true

if echo "$CHECK_OUTPUT" | grep -q "up to date"; then
    log "Already up to date."
    date +%s > "$CHECK_FILE"
    rm -f "$PENDING_FILE"
    exit 0
fi

if echo "$CHECK_OUTPUT" | grep -q "commits behind"; then
    COMMITS=$(echo "$CHECK_OUTPUT" | grep -oP '\d+(?= commits behind)')
    VER=$(hermes --version | head -1)
    MSG="⚙️ Auto-Update Check\n\nHermes is ${COMMITS} commits behind.\nCurrent: ${VER}\n\n⏳ Auto-apply scheduled in 10 minutes.\nRun \`hermes update\` now or create ~/.hermes/.pause-auto-update to skip."

    log "Update found: $COMMITS commits behind."
    date +%s > "$CHECK_FILE"
    date +%s > "$PENDING_FILE"

    send_notification "$MSG"
    exit 0
fi

log "WARNING: Unexpected output: $CHECK_OUTPUT"
exit 1
