#!/bin/bash
# setup.sh — One-time configuration for hermes-auto-updater notifications.
# This is run AFTER the skill is installed, not during install itself.
set -euo pipefail

HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
NOTIFY_DIR="$HERMES_HOME/.auto-updater"
NOTIFY_CONF="$NOTIFY_DIR/notify.conf"
ENV_FILE="$HERMES_HOME/.env"

mkdir -p "$NOTIFY_DIR"

echo "=== Hermes Auto-Updater Setup ==="
echo ""

# ------------------------------------------------------------------
# Helper: read a key from .env
# ------------------------------------------------------------------
read_env() {
    local key="$1"
    [ -f "$ENV_FILE" ] || return 1
    grep "^${key}=" "$ENV_FILE" 2>/dev/null | head -1 | cut -d= -f2- | sed 's/^"//;s/"$//'
}

# ------------------------------------------------------------------
# Telegram
# ------------------------------------------------------------------
TG_TOKEN=$(read_env "TELEGRAM_BOT_TOKEN" || true)
TG_USERS=$(read_env "TELEGRAM_ALLOWED_USERS" || true)

if [ -n "${TG_TOKEN:-}" ] && [ -n "${TG_USERS:-}" ]; then
    echo "Found existing Telegram configuration in Hermes."
    read -rp "Enable Telegram notifications for auto-updater? [Y/n]: " yn
    if [[ ! "$yn" =~ ^[Nn]$ ]]; then
        UID_FIRST=$(echo "$TG_USERS" | cut -d',' -f1)
        cat > "$NOTIFY_CONF" <<EOF
# Auto-generated by hermes-auto-updater setup.sh
# $(date)
NOTIFY_CMD="curl -s -X POST https://api.telegram.org/bot${TG_TOKEN}/sendMessage \\
    -d chat_id=${UID_FIRST} \\
    -d text=\\\"\${msg}\\\" \\
    -d parse_mode=HTML > /dev/null 2>&1 || true"
EOF
        echo "  ✓ Telegram notifications enabled: $NOTIFY_CONF"
        echo ""
        echo "To disable later, run: rm $NOTIFY_CONF"
        exit 0
    fi
fi

echo "No messaging gateway configured or user declined."
echo "Auto-updater will run silently and log to ~/.hermes/logs/auto-update.log"
echo ""
echo "To enable notifications later, re-run this setup script:"
echo "  bash ~/.hermes/skills/devops/hermes-auto-updater/scripts/setup.sh"
